// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDce9Sdqn9VRaZX0FjhDF9YIMD3F2zKZF0',
    appId: '1:456980050865:web:02449c93eee5fd60934390',
    messagingSenderId: '456980050865',
    projectId: 'chat-app-cdcd7',
    authDomain: 'chat-app-cdcd7.firebaseapp.com',
    storageBucket: 'chat-app-cdcd7.appspot.com',
    measurementId: 'G-GTLNCHLK41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCZdFV53eZ-HwKr1aP9AS6iz7aIjazyDw',
    appId: '1:456980050865:android:d8022508caa2e75e934390',
    messagingSenderId: '456980050865',
    projectId: 'chat-app-cdcd7',
    storageBucket: 'chat-app-cdcd7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7IoiKIh3AuOqpOOGZ4f-SFAz6i7Ug9mc',
    appId: '1:456980050865:ios:41515184da39cb3f934390',
    messagingSenderId: '456980050865',
    projectId: 'chat-app-cdcd7',
    storageBucket: 'chat-app-cdcd7.appspot.com',
    iosClientId: '456980050865-o52l4itbsg6umgf4396kv8pe5adhgjm8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7IoiKIh3AuOqpOOGZ4f-SFAz6i7Ug9mc',
    appId: '1:456980050865:ios:41515184da39cb3f934390',
    messagingSenderId: '456980050865',
    projectId: 'chat-app-cdcd7',
    storageBucket: 'chat-app-cdcd7.appspot.com',
    iosClientId: '456980050865-o52l4itbsg6umgf4396kv8pe5adhgjm8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
